runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/(.*)
  static_files: static/app/\1
  upload: static/app/(.*)

- url: /images/(.*)
  static_files: static/app/images/\1
  upload: static/app/images/(.*)

- url: /.*
  script: main.app